# Menus
menu:
  Services: services
  Portfolio: portfolio
  Articles: articles
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 60
        height: 60
        url: images/jr.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/rojo.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Robert Jordan
        author_title: Team Builder
        location: Boulder, Colorado
        follow: https://github.com/rojosnow
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/images/favicon.ico # path to favicon
    social_links:
        github: http://github.com/rojosnow
        twitter: /
        facebook: /
        rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag

# Search
search:
    insight: false # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: hexo-theme-icarus # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
